#!/usr/bin/env ruby
require 'optparse'
require_relative "../lib/convert2ascii/webcam2ascii"


options = {}
OptionParser.new do |parser|
  parser.banner = "Usage: webcam2ascii [options]"
  parser.on("--version", "version") do |v|
    puts "convert2ascii/webcam2ascii: v#{::Convert2Ascii::VERSION}"
    puts "author: Mark24"
    puts "mail: mark.zhangyoung@gmail.com"
    puts "project: https://github.com/mark24Code/convert2ascii"
    return
  end

  parser.on("-dDEVICE", "--device=DEVICE", "webcam device (default: 0)") do |device|
    options[:device] = device
  end

  parser.on("-fFPS", "--fps=FPS", Integer, "frames per second (default: 10)") do |fps|
    options[:fps] = fps
  end

  parser.on("-wWIDTH", "--width=WIDTH", Integer, "display width (integer)") do |width|
    options[:width] = width
  end

  parser.on("-sSTYLE", "--style=STYLE", "ascii style: ['color'| 'text']") do |style|
    options[:style] = style

    styles = ["color", "text"]
    unless styles.include? options[:style]
      puts "Error: --style option must be [\"color\" | \"text\"]."
      exit 1
    end
  end

  parser.on("-b", "--block", "ascii color style use BLOCK or not [ true | false ] ") do |color_block|
    options[:color_block] = color_block || false
  end
end.parse!

puts "Starting webcam ASCII capture..."
puts "Device: #{options[:device] || 0}"
puts "FPS: #{options[:fps] || 10}"
puts "Width: #{options[:width] || 'auto'}"
puts "Style: #{options[:style] || 'color'}"
puts ""

Convert2Ascii::Webcam2Ascii.new(**options).start
